services:

  trade-imports-dynamics-gateway:
    container_name: trade-imports-dynamics-gateway
    build:
      context: .
      target: development
    ports:
      - '8085:8085'
    environment:
      PORT: 8085
      SERVICE_VERSION: 0.0.0-local
      ENVIRONMENT: local
      LOG_LEVEL: DEBUG
      SPRING_PROFILES_ACTIVE: local
    networks:
      - trade-imports-tenant

networks:
  trade-imports-tenant:
    name: trade-imports-tenant
